version: '3.8'

services:
  backend-db:
    image: postgres:15
    container_name: backend-db
    restart: always
    environment:
      POSTGRES_DB: leiloaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - leiloaria-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d leiloaria"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  app_data:

networks:
  leiloaria-network:
    driver: bridge
